### ISSUE TITLE
错误码101账号密码错误

### ISSUE THREAD

**Issue by Kyrie-leon** [zimin9/WoZaiXiaoYuanPuncher#1]
试了5次账号被冻结了24小时，哪里设置的有问题吗🤔

**Comment by zimin9** [comment]
这个问题我也有遇到过。
你等24小时后，在小程序里修改一下密码。然后用新的账号密码登录试试。我是这样解决的。

而我新注册的号却没有这个问题

**Comment by HotoCocoaco** [comment]
> 这个问题我也有遇到过。
> 你等24小时后，在小程序里修改一下密码。然后用新的账号密码登录试试。我是这样解决的。
> 
> 而我新注册的号却没有这个问题

改了密码，用新密码登入还是不成功。

**Comment by zimin9** [comment]
> > 这个问题我也有遇到过。
> > 你等24小时后，在小程序里修改一下密码。然后用新的账号密码登录试试。我是这样解决的。
> > 而我新注册的号却没有这个问题
> 
> 改了密码，用新密码登入还是不成功。

你是改成纯小写字母密码吗，如果不是可以再试试，我是可以登陆的。
如果还是不行记得在issue说一下，我看下是不是请求头设置有问题。

**Comment by Chorer** [comment]
今天遇到了和楼上一样的情况（返回了 101 的错误码，提示账户出错）。感觉模拟登录这块有点问题，可能对方做了检测，你要是频繁进行登录操作（因为每次打卡都会调 login 函数），他会给你“账户出错”的警告，这之后如果又连续登录达到 5 次，就会冻结你的账号。

暂时的解决方案还是抓包，然后手动设置 jwsession，不要调 login 函数了。这样还是可以打卡的。所以在想要不只进行一次登录，之后就一直使用首次登录拿到的 jwsession？反正它的有效期貌似挺长的

**Comment by zimin9** [comment]
> 今天遇到了和楼上一样的情况（返回了 101 的错误码，提示账户出错）。感觉模拟登录这块有点问题，可能对方做了检测，你要是频繁进行登录操作（因为每次打卡都会调 login 函数），他会给你“账户出错”的警告，这之后如果又连续登录达到 5 次，就会冻结你的账号。
> 
> 暂时的解决方案还是抓包，然后手动设置 jwsession，不要调 login 函数了。这样还是可以打卡的。所以在想要不只进行一次登录，之后就一直使用首次登录拿到的 jwsession？反正它的有效期貌似挺长的

手动设置JWSESSION的话，又回到原来的老路上了，没办法真正“自动化”。
引入数据库做个缓存JWSESSION的表，JWSESSION失效后再自动登录获取新的。这样可能好点。
（话说我从七月底到现在，自动登陆打卡一直没有问题……）

**Comment by Chorer** [comment]
> > 今天遇到了和楼上一样的情况（返回了 101 的错误码，提示账户出错）。感觉模拟登录这块有点问题，可能对方做了检测，你要是频繁进行登录操作（因为每次打卡都会调 login 函数），他会给你“账户出错”的警告，这之后如果又连续登录达到 5 次，就会冻结你的账号。
> > 暂时的解决方案还是抓包，然后手动设置 jwsession，不要调 login 函数了。这样还是可以打卡的。所以在想要不只进行一次登录，之后就一直使用首次登录拿到的 jwsession？反正它的有效期貌似挺长的
> 
> 手动设置JWSESSION的话，又回到原来的老路上了，没办法真正“自动化”。
> 引入数据库做个缓存JWSESSION的表，JWSESSION失效后再自动登录获取新的。这样可能好点。
> （话说我从七月底到现在，自动登陆打卡一直没有问题……）

嗯嗯，能自动化最好了 你是一直没有遇到账户出错的问题吗 :joy:

**Comment by LLinVIP** [comment]
这个小程序比较邪门，随便注册了个号现在退也退不出去了

**Comment by HotoCocoaco** [comment]
> > > 这个问题我也有遇到过。
> > > 你等24小时后，在小程序里修改一下密码。然后用新的账号密码登录试试。我是这样解决的。
> > > 而我新注册的号却没有这个问题
> > 
> > 
> > 改了密码，用新密码登入还是不成功。
> 
> 你是改成纯小写字母密码吗，如果不是可以再试试，我是可以登陆的。
> 如果还是不行记得在issue说一下，我看下是不是请求头设置有问题。

改成了纯英文密码，成功登入。

**Comment by zimin9** [comment]
> 这个小程序比较邪门，随便注册了个号现在退也退不出去了

这是因为小程序后台把你的微信号和这个新号捆绑在一起了，每次打开小程序只要获取了你的openid就立即登陆新号了。可以通过修改密码解绑，可以试一下。

**Comment by LLinVIP** [comment]
> > 这个小程序比较邪门，随便注册了个号现在退也退不出去了
> 
> 这是因为小程序后台把你的微信号和这个新号捆绑在一起了，每次打开小程序只要获取了你的openid就立即登陆新号了。可以通过修改密码解绑，可以试一下。

感谢回复，我去试一下。

**Comment by uiolee** [comment]
在手机上手动登陆也是这样的，每次登陆都提醒密码错误，需要找回密码重新登陆。过了一段时间再登陆时密码又错误。感觉是小程序的问题。btw我用的是纯数字密码，不知道有没有关系
