### ISSUE TITLE
“myArea”参数问题

### ISSUE THREAD

**Issue by 1486308032** [zimin9/WoZaiXiaoYuanPuncher#11]
抓包每日健康打卡中Post的数据没有“myArea” ，这个参数是干嘛的？😁

**Comment by zimin9** [comment]
这个脚本是用于日检日报的。

需要健康打卡的话，可以看一下Action版的脚本，有热心网友写了这个功能。

**Comment by zimin9** [comment]
请顺便提交相应抓包记录，以便检查
