### ISSUE TITLE
Docker版本来了

### ISSUE THREAD

**Issue by ccqstark** [zimin9/WoZaiXiaoYuanPuncher#12]
作者你好，看到你的计划中有Docker版的设想，我基于你的仓库开发了Docker版
[ccqstark/WoZaiXiaoYuanPuncher-Docker](https://github.com/ccqstark/WoZaiXiaoYuanPuncher-Docker)
由于忘记fork直接clone了所以没法提PR，所以这里跟你说一声哈😁，算是又新增了一个版本

**Comment by zimin9** [comment]
不好意思，新学期有点忙，现在才看到你的issue。谢谢贡献！我会在README里加入你仓库的链接的。
