### ISSUE TITLE
4月17日我在校园打卡失败

### ISSUE THREAD

**Issue by 1v7w** [zimin9/WoZaiXiaoYuanPuncher#15]
尝试使用jwsession打卡...
返回`{'code': 7, 'message': '服务异常(7)'}`

**Comment by xyz2629** [comment]
4月17日同，发生相同错误

**Comment by zimin9** [comment]
如果情况一直存在，而手动打卡正常，可能是我在校园做了更新。

目前我学校已停用我在校园，无法进一步抓包分析，还望各位大佬分析一下情况。

**Comment by sizau** [comment]
https://www.sizau.com/a/wzxy-signature.html

SHA256校验

**Comment by zimin9** [comment]
> https://www.sizau.com/a/wzxy-signature.html
> 
> SHA256校验

感谢大佬提供解决方法！

**Comment by Alicil** [comment]
> > https://www.sizau.com/a/wzxy-signature.html
> > SHA256校验
> 
> 感谢大佬提供解决方法！

这个怎么添加代码？

**Comment by zimin9** [comment]
> > > https://www.sizau.com/a/wzxy-signature.html
> > > SHA256校验
> > 
> > 
> > 感谢大佬提供解决方法！
> 
> 这个怎么添加代码？

请仔细阅读大佬的文章，将province、timestamp、city三个字段组合后进行SHA256加密，再发送。

代码示例已在文中列举。

**Comment by zimin9** [comment]
> > > https://www.sizau.com/a/wzxy-signature.html
> > > SHA256校验
> > 
> > 
> > 感谢大佬提供解决方法！
> 
> 这个怎么添加代码？

请仔细阅读大佬的文章，将province、timestamp、city三个字段组合后进行SHA256加密，再发送。

代码示例已在文中列举。

**Comment by 1v7w** [comment]
> https://www.sizau.com/a/wzxy-signature.html
> 
> SHA256校验
@sizau 
我在校园更新后 我的fiddler无法抓到包了  请问你是怎么抓到的。
我的fiddler的版本是v5.0.20204.45441
